[default]
timeout = 30

[printables_vcdesign]
title = "Printables — VC Design"
url = "https://www.printables.com/@VC_Design/models"
entrySelector = "article.card"
titleSelector = ".card-content h5"
linkSelector = ".card-content h5 a"
contentSelector = "article.card picture source"
