name: Pages Debug

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Pages Debug $(date -u) on $GITHUB_REF @ $GITHUB_SHA"


