name: CI Ping

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ping $(date -u) on $GITHUB_REF @ $GITHUB_SHA"


